services:
  tts:
    environment:
      TTS_ACCELERATOR: ${TTS_ACCELERATOR:-cuda}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
